services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - api
    networks:
      - internal_routing

  api:
    build:
      context: ./api
      dockerfile: build/http.Dockerfile
    container_name: api
    networks:
      - internal_routing

  web:
    build:
      context: ./web
      dockerfile: build/web.Dockerfile
    container_name: web
    networks:
      - internal_routing

networks:
  internal_routing:
    driver: bridge